name = "ComoniconBuilder"
uuid = "0acea522-3a8c-4b93-9211-1fc67cbf95d9"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.3"

[deps]
ComoniconOptions = "a25bc8ac-9d24-42b2-8edd-3d267ec19fc5"
ComoniconTypes = "d0eb39ce-029e-40d1-add6-e32b3165f6a3"
ComoniconZSHCompletion = "dcf03e4a-d036-4ede-96c9-024e9e9eed12"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[compat]
ComoniconOptions = "0.1"
ComoniconTypes = "0.2"
ComoniconZSHCompletion = "0.2"
PackageCompiler = "1"
julia = "1.6.1"

[extras]
ComoniconTestUtils = "53b67e40-53a7-4335-973f-e3e901fe4865"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg", "ComoniconTestUtils"]
