name = "ComoniconBuilder"
uuid = "0acea522-3a8c-4b93-9211-1fc67cbf95d9"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ComoniconOptions = "a25bc8ac-9d24-42b2-8edd-3d267ec19fc5"
ComoniconTargetExpr = "d6dfd36b-42f3-4a9f-a1cb-6f1a052fed42"
ComoniconTypes = "d0eb39ce-029e-40d1-add6-e32b3165f6a3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[compat]
PackageCompiler = "1"
ComoniconTypes = "0.1"
ComoniconOptions = "0.1"
ComoniconTargetExpr = "0.1"
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
